// solid/features/notification/components/Notifications.tsx
/** @jsxImportSource solid-js */
import type { JSX } from 'solid-js';

// export function Notifications(props: {
// 	store?: any;
// 	class?: string;
// 	position?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
// }): JSX.Elemen

import { For } from 'solid-js';
import { notificationStore } from '../notificationStore';

export function Notifications(): JSX.Element {
	const removeNotificationHandler = (id?: string) => {
		if (id) notificationStore.remove(id);
	};

	return (
		<div class="notifications">
			<div class="z-50 position-top-right default-position-style-top-right">
				<For each={notificationStore.get().list}>
					{(notification) => (
						<div
							class={`z-50 notification default-notification-style default-notification-${notification.type}`}
							aria-live="polite"
						>
							<div
								class={`z-50 notification-content default-notification-style-content default-notification-${notification.type}`}
							>
								<pre>{notification.message}</pre>
							</div>
							<button
								type="button"
								class={`z-50 notification-button default-notification-style-button default-notification-${notification.type}`}
								onClick={() => removeNotificationHandler(notification.id)}
								aria-label="delete notification"
							>
								&times;
							</button>
						</div>
					)}
				</For>
			</div>
		</div>
	);
}

// vue/features/notification/components/Notifications.vue
<script setup lang="ts">
import { useNotification } from '../notificationStore';

const store = useNotification();
const removeNotificationHandler = (id?: string) => {
	if (id) store.remove(id);
};
</script>

<template>
  <div class="notifications">
    <div class="z-50 position-top-right default-position-style-top-right">
      <div v-for="n in store.notifications" :key="n.id"
        class="z-50 notification default-notification-style"
        :class="`default-notification-${n.type}`"
        role="status" aria-live="polite">
        <div class="z-50 notification-content default-notification-style-content"
          :class="`default-notification-${n.type}`">
          <slot>
            <pre>{{ n.message }}</pre>
          </slot>
        </div>
        <button class="z-50 notification-button default-notification-style-button"
          :class="`default-notification-${n.type}`" @click="removeNotificationHandler(n.id)"
          aria-label="delete notification">
          &times;
        </button>
      </div>
    </div>
  </div>
</template>
