// solid2/features/notification/components/Notifications.tsx
import type { JSX } from '@solidjs/web';
import { For } from 'solid-js';
import type {
	NotificationPosition,
	NotificationStore,
} from '../notificationStore';

export interface NotificationsProps {
	store: NotificationStore;
	class?: string;
	position?: NotificationPosition;
}

export function Notifications(props: NotificationsProps): JSX.Element {
	return (
		<div class={`notifications ${props.class || ''}`}>
			<div
				class={`z-50 position-top-right default-position-style-top-right ${props.position ? `position-${props.position}` : ''}`}
			>
				<For each={props.store.get().list}>
					{(notification) => (
						<div
							class={`z-50 notification default-notification-style default-notification-${notification.type}`}
							aria-live="polite"
						>
							<div
								class={`z-50 notification-content default-notification-style-content default-notification-${notification.type}`}
							>
								<div>{notification.message}</div>
							</div>
							<button
								type="button"
								class={`z-50 notification-button default-notification-style-button default-notification-${notification.type}`}
								onClick={() => {
									if (notification.id) props.store.remove(notification.id);
								}}
								aria-label="delete notification"
							>
								&times;
							</button>
						</div>
					)}
				</For>
			</div>
		</div>
	);
}

// vue/features/notification/components/Notifications.vue
<script setup lang="ts">
import type { NotificationPosition } from '../notificationStore';
import { useNotification } from '../notificationStore';

defineProps<{
	position?: NotificationPosition;
}>();

const store = useNotification();
const removeNotificationHandler = (id?: string) => {
	if (id) store.remove(id);
};
</script>

<template>
  <div class="notifications">
    <div class="z-50 position-top-right default-position-style-top-right"
      :class="position ? `position-${position}` : ''">
      <div v-for="n in store.list" :key="n.id"
        class="z-50 notification default-notification-style"
        :class="`default-notification-${n.type}`">
        <div class="z-50 notification-content default-notification-style-content"
          :class="`default-notification-${n.type}`">
          <slot>
            <div>{{ n.message }}</div>
          </slot>
        </div>
        <button class="z-50 notification-button default-notification-style-button"
          :class="`default-notification-${n.type}`" @click="removeNotificationHandler(n.id)"
          aria-label="delete notification">
          &times;
        </button>
      </div>
    </div>
  </div>
</template>
