// solid/features/notification/Notifications.tsx
/** @jsxImportSource solid-js */
import type { JSX } from "solid-js";
import type { NotificationStore } from "./store.ts";

export function Notifications(props: {
	store: NotificationStore;
	class?: string;
	position?: "top-right" | "top-left" | "bottom-right" | "bottom-left";
}): JSX.Element {
	const items = () => props.store.state.items;
	const positionClass = () => `pos-${props.position ?? "top-right"}`;
	return (
		<div class={(props.class ?? "") + " gw-notifications " + positionClass()}>
			{items().map((n) => (
				<div class="gw-notification" data-type={n.type}>
					{n.message}
				</div>
			))}
		</div>
	);
}

// vue/features/notification/components/Notifications.tsx
import type { Component, PropType } from 'vue';
import { defineComponent } from 'vue';
import type { NotificationStore } from '../store.ts';

const Notifications: Component = defineComponent({
	name: 'Notifications',
	props: {
		store: Object as PropType<NotificationStore>,
		class: String,
		position: {
			type: String as PropType<
				'top-right' | 'top-left' | 'bottom-right' | 'bottom-left'
			>,
			default: 'top-right',
		},
	},
	setup(props) {
		return () => (
			<div
				class={
					[
						props.class as any,
						'gw-notifications',
						`pos-${props.position}`,
					] as any
				}
			>
				{props.store.state.items.map((n) => (
					<div class="gw-notification" data-type={n.type} key={n.id}>
						{n.message}
					</div>
				))}
			</div>
		);
	},
});

export default Notifications;
