// vue/features/modal/components/Modal.tsx
import type { Component, PropType } from 'vue';
import { defineComponent } from 'vue';
import type { ModalStore } from '../store';

const Modal: Component = defineComponent({
	name: 'Modal',
	props: { store: Object as PropType<ModalStore>, class: String },
	setup(props) {
		return () =>
			props.store.state.isOpen ? (
				<div class={['gw-modal', (props as any).class]}>
					<div class="gw-modal__panel">
						<div class="gw-modal__body">
							{props.store.state.options.message ? (
								<div>{props.store.state.options.message}</div>
							) : props.store.state.options.html ? (
								<div innerHTML={props.store.state.options.html as any} />
							) : (
								<></>
							)}
						</div>
						<div class="gw-modal__actions">
							<button
								type="button"
								class="gw-modal__btn"
								onClick={() => props.store.yes()}
							>
								OK
							</button>
							<button
								type="button"
								class="gw-modal__btn"
								onClick={() => props.store.no()}
							>
								Cancel
							</button>
						</div>
					</div>
				</div>
			) : null;
	},
});

export default Modal;

// solid/features/modal/Modal.tsx
/** @jsxImportSource solid-js */
import type { JSX } from "solid-js";
import type { ModalStore } from "./store.ts";
import { Show } from "solid-js";

export function Modal(props: {
	store: ModalStore;
	class?: string;
}): JSX.Element {
	const state = () => props.store.state;
	return (
		<Show when={state().isOpen}>
			<div class={"gw-modal " + (props.class ?? "")}> 
				<div class="gw-modal__panel">
					<div class="gw-modal__body">
						{state().options.message ? (
							<div>{state().options.message}</div>
						) : state().options.html ? (
							<div innerHTML={state().options.html} />
						) : (
							<></>
						)}
					</div>
					<div class="gw-modal__actions">
						<button class="gw-modal__btn" onClick={() => props.store.yes()}>OK</button>
						<button class="gw-modal__btn" onClick={() => props.store.no()}>Cancel</button>
					</div>
				</div>
			</div>
		</Show>
	);
}
