// solid/features/loading/Loading.tsx
/** @jsxImportSource solid-js */
import type { JSX } from "solid-js";
import type { LoadingStore } from "./store.ts";
import { Show } from "solid-js";

export function Loading(props: {
	store?: LoadingStore;
	class?: string;
	style?: string | JSX.CSSProperties;
	show?: boolean;
}): JSX.Element {
	const visible = () => props.show ?? props.store?.isLoading ?? false;
	return (
		<Show when={visible()}>
			<div class={"gw-loading " + (props.class ?? "")} style={props.style as any}>
				<span class="gw-loading__spinner" />
			</div>
		</Show>
	);
}

// vue/features/loading/components/Loading.tsx
import { defineComponent, computed } from 'vue';
import type { PropType, CSSProperties, Component } from 'vue';
import type { LoadingStore } from '../store.ts';

const Loading: Component = defineComponent({
	name: 'Loading',
	props: {
		store: Object as PropType<LoadingStore | undefined>,
		class: String,
		style: [String, Object] as PropType<string | CSSProperties>,
		show: Boolean,
	},
	setup(props) {
		const visible = computed(
			() => (props as any).show ?? props.store?.isLoading.value ?? false,
		);
		return () =>
			visible.value ? (
				<div
					class={['gw-loading', (props as any).class]}
					style={props.style as any}
				>
					<span class="gw-loading__spinner" />
				</div>
			) : null;
	},
});

export default Loading;
